//
// Generated file, do not edit! Created by nedtool 5.4 from MyMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __MYMSG_M_H
#define __MYMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>MyMsg.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet MyMsg
 * {
 *     int sourceId;
 *     int destId;
 *     string packetType;
 *     int packetId;
 * }
 * </pre>
 */
class MyMsg : public ::omnetpp::cPacket
{
  protected:
    int sourceId;
    int destId;
    ::omnetpp::opp_string packetType;
    int packetId;

  private:
    void copy(const MyMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MyMsg&);

  public:
    MyMsg(const char *name=nullptr, short kind=0);
    MyMsg(const MyMsg& other);
    virtual ~MyMsg();
    MyMsg& operator=(const MyMsg& other);
    virtual MyMsg *dup() const override {return new MyMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);
    virtual int getDestId() const;
    virtual void setDestId(int destId);
    virtual const char * getPacketType() const;
    virtual void setPacketType(const char * packetType);
    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MyMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MyMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MYMSG_M_H

